version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: zoom_postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: zoom_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d zoom_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: .
    container_name: zoom_web_app
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/zoom_db
      - PORT=3000
      - GOOGLE_CLIENT_ID=68734281789-7m9ak2vclsaoji4amn3da4p9826lsalp.apps.googleusercontent.com
    depends_on:
      db:
        condition: service_healthy
    restart: always

volumes:
  postgres_data:
